data_srcs:
  save_path: "data_srcs/indexed"
  websites:
    syllabus: "https://www.escalab.org/classes/cs203-2024sp/"
  pdf_dir: "data_srcs/pdfs/"

db_path: "new_user_logs.db"

aqua_cfg:
    chunk_size: 128
    overlap_ratio: 0.5
    top_k: 15
    max_dist: 0.75
